"""Generate optimized robots.txt for dental practice sites.

Strategy: Block training bots (protect content IP) but allow retrieval/search
bots so the practice appears in AI-generated answers.
"""

from __future__ import annotations

from geo_agent.config import Customer


def generate_robots_txt(customer: Customer) -> str:
    """Generate robots.txt that maximizes AI search visibility."""
    domain = customer.domain
    return f"""# robots.txt — Generated by PracticeRank GEO Agent for {customer.name}
# Strategy: Block AI training crawlers, allow AI search/retrieval bots
# so patients can find this practice through ChatGPT, Claude, Perplexity, etc.

# BLOCK training bots (they scrape content for model training)
User-agent: GPTBot
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: meta-externalagent
Disallow: /

User-agent: Applebot-Extended
Disallow: /

# ALLOW retrieval/search bots (they fetch content for real-time AI answers)
User-agent: ChatGPT-User
Allow: /

User-agent: Claude-SearchBot
Allow: /

User-agent: Claude-User
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Perplexity-User
Allow: /

User-agent: Googlebot
Allow: /

User-agent: Applebot
Allow: /

# Standard crawlers
User-agent: *
Allow: /

Sitemap: https://{domain}/sitemap.xml
"""
