"""Generate optimized robots.txt for business websites.

Strategy: Block training bots (protect content IP) but allow retrieval/search
bots so the business appears in AI-generated answers.
"""

from __future__ import annotations

from geo_agent.business_profiles import get_profile
from geo_agent.config import Customer


def generate_robots_txt(customer: Customer) -> str:
    """Generate robots.txt that maximizes AI search visibility."""
    profile = get_profile(customer)
    domain = customer.domain
    return f"""# robots.txt — Generated by PracticeRank GEO Agent for {customer.name}
# Strategy: Block AI training crawlers, allow AI search/retrieval bots
# so {profile.customer_term} can find this business through ChatGPT, Claude, Perplexity, etc.

# BLOCK training bots (they scrape content for model training, not search)
User-agent: GPTBot
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: meta-externalagent
Disallow: /

User-agent: Applebot-Extended
Disallow: /

User-agent: Bytespider
Disallow: /

User-agent: cohere-ai
Disallow: /

User-agent: AI2Bot
Disallow: /

User-agent: Scrapy
Disallow: /

# ALLOW retrieval/search bots (they fetch content for real-time AI answers)
User-agent: ChatGPT-User
Allow: /

User-agent: Claude-SearchBot
Allow: /

User-agent: Claude-User
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Perplexity-User
Allow: /

User-agent: Amazonbot
Allow: /

User-agent: YouBot
Allow: /

User-agent: Googlebot
Allow: /

User-agent: Applebot
Allow: /

# Standard crawlers
User-agent: *
Allow: /

Sitemap: https://{domain}/sitemap.xml
Llms-txt: https://{domain}/llms.txt
"""
