"""Operational digests — push what needs doing to the team instead of waiting
for someone to open the dashboard.

- monthly_fatjoe_digest: day-1 marching orders for Dan — exactly what to order
  this month per paying client, with deadlines.
- daily_attention_digest: anything that needs action today (overdue FATJOE,
  paid-but-no-access-email, pending access, awaiting approval).

Both go to the Account Manager (Dan) and CC the accounts owner (Kody). Sent via
Resend. Recipients are env-overridable.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from geo_agent import action_items, fatjoe_plan

logger = logging.getLogger(__name__)

# Account Manager (primary) + accounts owner (CC). Overridable via env.
AM_EMAIL = os.environ.get("ACCOUNT_MANAGER_EMAIL", "dtoone@practicerank.ai")
OWNER_EMAIL = os.environ.get("ACCOUNTS_EMAIL", "kdoherty@practicerank.ai")
FROM_ADDR = os.environ.get("DIGEST_FROM", "PracticeRank <reports@practicerank.ai>")
DASHBOARD_URL = os.environ.get("DASHBOARD_URL", "https://admin.practicerank.ai")

_SEV_COLOR = {"critical": "#dc2626", "warning": "#f59e0b", "info": "#0284c7"}
_CLOCK_COLOR = {"overdue": "#dc2626", "soon": "#f59e0b", "ok": "#0284c7"}


def _send(subject: str, html: str, to: list[str] | None = None,
          cc: list[str] | None = None) -> bool:
    """Send an email via Resend. Returns True on success."""
    key = os.environ.get("RESEND_API_KEY", "")
    if not key:
        logger.warning("No RESEND_API_KEY — digest not sent: %s", subject)
        return False
    to = to or [AM_EMAIL]
    cc = cc if cc is not None else [OWNER_EMAIL]
    try:
        import httpx
        resp = httpx.post(
            "https://api.resend.com/emails",
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={"from": FROM_ADDR, "to": to, "cc": cc, "subject": subject, "html": html},
            timeout=15.0,
        )
        if resp.status_code in (200, 201):
            logger.info("Digest sent: %s -> %s cc %s", subject, to, cc)
            return True
        logger.warning("Digest send failed %s: %s", resp.status_code, resp.text[:200])
    except Exception as e:  # noqa: BLE001
        logger.warning("Digest send error: %s", e)
    return False


def _shell(title: str, subtitle: str, inner: str) -> str:
    return f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:720px;margin:0 auto;color:#0f172a;">
      <div style="background:#0f1117;color:#fff;padding:20px 24px;border-radius:12px 12px 0 0;">
        <h1 style="margin:0;font-size:19px;">{title}</h1>
        <p style="margin:4px 0 0;opacity:.8;font-size:13px;">{subtitle}</p>
      </div>
      <div style="padding:18px 24px;background:#f8fafc;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px;">
        {inner}
        <p style="font-size:12px;color:#94a3b8;text-align:center;margin-top:18px;">
          Auto-generated by PracticeRank · <a href="{DASHBOARD_URL}">Open dashboard</a>
        </p>
      </div>
    </div>
    """


# ───────────────────────────── Monthly FATJOE digest ─────────────────────────────

def build_monthly_fatjoe(db, now: datetime | None = None) -> tuple[str, str, int]:
    """Return (subject, html, order_count) for the month's FATJOE orders."""
    now = now or datetime.now(timezone.utc)
    month = now.strftime("%B %Y")
    rows = []
    total_due = 0
    for cust in db.list_customers():
        sub = db.get_subscription_for_customer(cust["id"])
        plan_name = sub["plan_name"] if sub else None
        if not fatjoe_plan.normalize_tier(plan_name):
            continue
        due = fatjoe_plan.due_orders(db, cust["id"], plan_name, now=now)
        if not due["total_due"]:
            continue
        total_due += due["total_due"]
        items_html = ""
        for i in due["items"]:
            if not i["qty_due"]:
                continue
            spec = (f"{i['qty_due']}× {i['type_label']}"
                    + (f" DR{i['dr_tier']}–{i['dr_tier'] + 10}" if i['dr_tier'] else ""))
            items_html += (f"<li><b>{spec}</b> — <span style='color:#475569;'>{i['note']}</span></li>")
        clock = (f"<span style='color:{_CLOCK_COLOR.get(due['severity'], '#0284c7')};font-weight:700;'>"
                 + (f"OVERDUE by {-due['days_left']}d" if due['severity'] == 'overdue'
                    else f"due by {due['deadline']} ({due['days_left']}d left)") + "</span>")
        rows.append(
            f"<div style='background:#fff;border:1px solid #e5e7eb;border-left:4px solid "
            f"{_CLOCK_COLOR.get(due['severity'], '#0284c7')};border-radius:8px;padding:12px 14px;margin-bottom:10px;'>"
            f"<div style='font-weight:700;'>{cust['name']} "
            f"<span style='font-weight:500;color:#64748b;'>· {due['label']} · {clock}</span></div>"
            f"<ul style='margin:6px 0 0;padding-left:18px;font-size:14px;'>{items_html}</ul></div>"
        )

    if not rows:
        inner = ("<p style='font-size:15px;'>✅ Nothing outstanding — every paying client's FATJOE "
                 "orders for this period are already logged. Nice work.</p>")
        return (f"FATJOE orders — {month}: all clear", _shell("FATJOE Monthly Orders", month, inner), 0)

    inner = (f"<p style='font-size:15px;margin-top:0;'><b>{total_due} order(s)</b> to place this month. "
             f"Order in the FATJOE reseller dashboard, then log each on the client's "
             f"<b>Backlinks &amp; Authority</b> tab so it tracks to delivery.</p>"
             + "".join(rows)
             + f"<p style='text-align:center;margin-top:14px;'><a href='{DASHBOARD_URL}/fatjoe' "
               f"style='background:#0f1117;color:#fff;padding:9px 18px;border-radius:8px;text-decoration:none;font-weight:600;'>"
               f"Open the order queue →</a></p>")
    return (f"FATJOE orders — {month}: {total_due} to place",
            _shell("FATJOE Monthly Orders", month, inner), total_due)


def monthly_fatjoe_digest(db, now: datetime | None = None) -> bool:
    subject, html, _ = build_monthly_fatjoe(db, now)
    return _send(subject, html)


# ───────────────────────────── Daily attention digest ─────────────────────────────

def build_daily_attention(db, now: datetime | None = None) -> tuple[str, str, int]:
    """Return (subject, html, urgent_count). Only items needing action are listed."""
    now = now or datetime.now(timezone.utc)
    today = now.strftime("%a %b %-d")
    blocks = []
    urgent = 0
    for cust in db.list_customers():
        if cust["status"] not in ("active", "onboarding"):
            continue
        items = action_items.customer_action_items(db, cust)
        actionable = [i for i in items if i["severity"] in ("critical", "warning")]
        if not actionable:
            continue
        urgent += len(actionable)
        chips = "".join(
            f"<li style='margin:2px 0;'><span style='display:inline-block;width:8px;height:8px;border-radius:50%;"
            f"background:{_SEV_COLOR.get(i['severity'], '#0284c7')};margin-right:7px;'></span>"
            f"<b>{i['label']}</b> <span style='color:#64748b;'>— {i['detail']}</span></li>"
            for i in actionable
        )
        blocks.append(
            f"<div style='background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:11px 14px;margin-bottom:9px;'>"
            f"<a href='{DASHBOARD_URL}/customer/{cust['id']}' style='font-weight:700;color:#0f172a;text-decoration:none;'>{cust['name']}</a>"
            f"<ul style='margin:6px 0 0;padding-left:4px;list-style:none;font-size:14px;'>{chips}</ul></div>"
        )

    # Global: paid Stripe subscriptions not linked to any customer (silent mismatch).
    unmatched = [s for s in db.list_subscriptions()
                 if not s["customer_id"] and s["status"] in action_items.PAID_STATUSES]
    unmatched_html = ""
    if unmatched:
        urgent += len(unmatched)
        lis = "".join(
            f"<li style='margin:2px 0;'><b>{s['plan_name'] or 'Subscription'}</b> "
            f"<span style='color:#64748b;'>— {s['stripe_customer_email'] or 'no email'} "
            f"(${(s['amount_cents'] or 0) // 100}/mo, paid but unlinked)</span></li>"
            for s in unmatched
        )
        unmatched_html = (
            f"<div style='background:#fff;border:1px solid #fca5a5;border-left:4px solid #dc2626;"
            f"border-radius:8px;padding:11px 14px;margin-bottom:9px;'>"
            f"<a href='{DASHBOARD_URL}/billing' style='font-weight:700;color:#991b1b;text-decoration:none;'>"
            f"{len(unmatched)} paid subscription(s) not linked to a client</a>"
            f"<ul style='margin:6px 0 0;padding-left:18px;font-size:14px;'>{lis}</ul></div>"
        )

    if not blocks and not unmatched_html:
        return ("", "", 0)  # nothing urgent — caller skips the send

    inner = (f"<p style='font-size:15px;margin-top:0;'><b>{urgent} item(s)</b> need attention.</p>"
             + unmatched_html + "".join(blocks))
    return (f"⚠️ PracticeRank — {urgent} item(s) need attention",
            _shell("Needs Attention", today, inner), urgent)


def daily_attention_digest(db, now: datetime | None = None) -> bool:
    subject, html, urgent = build_daily_attention(db, now)
    if not urgent:
        logger.info("Daily attention digest: nothing urgent — not sending.")
        return False
    return _send(subject, html)
